### ISSUE TITLE
[QUESTION] - Why make this order 👇 ?

### ISSUE THREAD

**Issue by mateushnsoares** [Tibfib/eslint-plugin-import-helpers#32] opened 2020-08-19 10:41 UTC
Sorry for the new issue. When have a "^react" import a want that stays in the top but when have styled-components default import I want that stays on the top because In my style files I want the styled-components default import stays before of react-icons. But when I import the theme provider from styled-components ( named export ) I want him to stay after react
I try this:
```jso
{
 rules: {
    "import-helpers/order-imports": [
      "error",
      {
        "newlinesBetween": "always",
        "groups": [
          [
            "/^react(?!-icons\/*)/", // also I tried"/^react(?!-icons)"
            "/styled-components/",
            "/react-icons/"
          ],
          "module",
          [
            "parent",
            "sibling",
            "index"
          ]
        ],
        "alphabetize": {
          "order": "asc",
          "ignoreCase": true
        }
      }
    ],
 }
}
```
but not work

**Comment by mateushnsoares** [comment] 2020-08-19 11:11
@Tibfib  pleaseee helpp me

**Comment by willhoney7** [comment] 2020-08-19 14:46
Hi @mateushnsoares,

The issue is that the order within a group is not enforced. For your react+styled-components+react-icons group, they are ordered alphabetically (see your "alphabetize" settings).

There's more discussion on this issue here https://github.com/Tibfib/eslint-plugin-import-helpers/issues/17. I'm going to close this one in favor of keeping all the conversation over there. Please comment over there if you have suggestions on how to address this. Thanks!

**Closed as completed by willhoney7** 2020-08-19 14:46 UTC

**Comment by mateushnsoares** [comment] 2020-08-19 17:30
Thx, sorry for the new issue.
