### ISSUE TITLE
How to separate modules that are only `import`

### ISSUE THREAD

**Issue by imrafaelcezar** [Tibfib/eslint-plugin-import-helpers#46] opened 2022-03-09 14:00 UTC
How the imports look like:
```ts
import Client from '~/structures/Client';
import 'dotenv/config';
```
How I would like it to be:
```ts
import Client from '~/structures/Client';

import 'dotenv/config';
```

How could I do this?

**Comment by willhoney7** [comment] 2022-04-14 16:37
As the docs mention, bare imports are not ordered because they usually contain side effects and the order matters.

https://github.com/Tibfib/eslint-plugin-import-helpers/blob/master/docs/rules/order-imports.md#:~:text=Unassigned%20imports%20are%20ignored%20(ex%3A%20import%20%27polyfill%27)%2C%20as%20the%20order%20they%20are%20imported%20in%20may%20be%20important.

Someone opened up a PR once to add support for this but it was never finished.

**Comment by willhoney7** [comment] 2022-04-14 16:38
closing since this is a duplicate of https://github.com/Tibfib/eslint-plugin-import-helpers/issues/35

**Closed as completed by willhoney7** 2022-04-14 16:37 UTC
